version: "3"

services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  go-service-1:
    build: ./path/to/go-service-1
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb

  go-service-2:
    build: ./path/to/go-service-2
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb

volumes:
  dbdata:
