version: "3"

services:
  db:
    build: ./database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhook
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/webhook/postgresql/data:/var/lib/webhook/postgresql/data
  webhook:
    build:
      context: .
      dockerfile: webhook/Dockerfile
    restart: always
    ports:
      - "8999:8999"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_NAME: webhook
      POSTGRES_PORT: 5432
