version: "3"

services:
  db:
    build: ./database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
  webhook:
    build:
      context: .
      dockerfile: webhook/Dockerfile
    restart: always
    ports:
      - "8999:8999"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb

